server:
  port: 8085
spring:
  application:
    name: provider
eureka:
  security:
    user:
      name: "luke"
      password: "123456"
  client:
    service-url:
      defaultZone: http://${eureka.security.user.name}:${eureka.security.user.password}@127.0.0.1:8081/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-demo1