server:
  port: 8084
spring:
  application:
    name: unreka_zuul
eureka:
  security:
    user:
      name: "luke"
      password: "123456"
  client:
    service-url:
      defaultZone: http://${eureka.security.user.name}:${eureka.security.user.password}@127.0.0.1:8081/eureka/
zuul:
  routes:
    common: /v1/common/**
    eureka_feign: /v1/feign/**